#!/bin/bash

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [[ "$BRANCH_NAME" == *"no branch"* ]]
then
  exit 0
fi

echo "Related redmine issue: "
exec < /dev/tty && read tid

re='^[0-9]+$'
if [[ $tid =~ $re ]] ; then
sed -i "2 s/^/\nhttps:\/\/redmine.net\/issues\/$tid #$tid\n/" $1
fi

